// <auto-generated />
using BankApplication.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankApplication.Persistance.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BankApplication.Domain.Entities.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountBalance = 7654m,
                            AccountNumber = "3019075149919263436240"
                        });
                });

            modelBuilder.Entity("BankApplication.Domain.Entities.CashMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Banknote10")
                        .HasColumnType("int");

                    b.Property<int>("Banknote100")
                        .HasColumnType("int");

                    b.Property<int>("Banknote20")
                        .HasColumnType("int");

                    b.Property<int>("Banknote200")
                        .HasColumnType("int");

                    b.Property<int>("Banknote50")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CashMachines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Banknote10 = 5,
                            Banknote100 = 5,
                            Banknote20 = 5,
                            Banknote200 = 5,
                            Banknote50 = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
